version: '3.7'

services:

  mysql:
    user: ${CUR_UID}
    networks:
      - nugurang-net
    image: mysql
    container_name: nugurang-mysql
    volumes:
      - /var/lib/files:/var/lib/files
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "nugurang"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  nextjs:
    user: ${CUR_UID}
    networks:
      - nugurang-net
    build: ./nugurang
    container_name: nugurang-nextjs
    volumes:
      - /var/lib/files:/var/lib/files
        ports:
      - "8080:3000"


volumes:
  nugurang-data:

networks:
  nugurang-net: {}