version: '3.7'

services:

  nugurang-db:
    user: ${CUR_UID}
    networks:
      - nugurang-net
    image: mariadb
    container_name: nugurang-db
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "nugurang"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  nugurang-front:
    user: ${CUR_UID}
    networks:
      - nugurang-net
    build: ./nugurang-front
    container_name: nugurang-front
    ports:
      - "8080:3000"

volumes:
  nugurang-data:

networks:
  nugurang-net: {}
