version: '3.7'
services:
  db:
    image: mysql
    container_name: nugurang-mysql
    volumes:
      - "mysql_data:/var/lib/mysql"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "nugurang"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

volumes:
    mysql_data:
