version: '3.7'

services:

  nugurang-db:
    user: ${CUR_UID}
    networks:
      - nugurang-net
    image: mariadb
    container_name: nugurang-db
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "nugurang"
      MYSQL_USER: "nugurang"
      MYSQL_PASSWORD: "nugurang"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  nugurang-front:
    user: ${CUR_UID}
    networks:
      - nugurang-net
    build: ./nugurang-front
    container_name: nugurang-front
    ports:
      - "8000:3000"

  nugurang-back:
    user: ${CUR_UID}
    networks:
      - nugurang-net
    build: ./nugurang-back
    container_name: nugurang-back
    ports:
      - "8001:8080"

  nugurang-dbadmin:
    depends_on:
      - nugurang-db
    user: ${CUR_UID}
    networks:
      - nugurang-net
    image: phpmyadmin
    container_name: nugurang-dbadmin
    environment:
      PMA_HOST: "nugurang-db"
      PMA_USER: "nugurang"
      PMA_PASSWORD: "nugurang"
    ports:
      - "8002:80"

volumes:
  nugurang-data:

networks:
  nugurang-net: {}
